# Site Info
title: ""
tagline: ""
description: ""
baseurl: ""
url: https://leehoshin.github.io
logo: ""

# Site configurations
#gems:
#  - jekyll-paginate
#markdown: kramdown
#kramdown:
#  input: GFM
#excerpt_separator: "<!— more —>"
sass:
  style: compressed
  sass_dir: _scss
#paginate:
#paginate_path: ''
#permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Hoshin Lee
  description: Hoshin Lee
  contact:
    github:    https://github.com/leehoshin
    email:    mailto:21400621@handong.edu

google_analytics_id: UA-159938300-1
